graphite:
  image: hopsoft/graphite-statsd
 # volumes:
 #   - ./graphite/config/storage-schemas.conf/:/opt/graphite/conf/storage-schemas.conf
  ports:
    - "80:80"
    - "2003:2003"
    - "8125:8125/udp"
    - "8126:8126"
elasticsearch:
  image: elasticsearch:latest
  command: elasticsearch -Des.network.host=0.0.0.0
  volumes:
    - ./elasticsearch/config:/etc/elasticsearch/
  ports:
    - "9200:9200"
logstash_stocks:
  image: logstash:latest
  command: logstash -f /etc/logstash/conf.d/logstash.conf
  volumes:
    - ./logstash_stocks/config:/etc/logstash/conf.d
  ports:
    - "5001:5001"
  links:
    - elasticsearch
    - graphite
logstash_operations:
  image: logstash:latest
  command: logstash -f /etc/logstash/conf.d/logstash.conf
  volumes:
    - ./logstash_operations/config:/etc/logstash/conf.d
  ports:
    - "5002:5002"
  links:
    - elasticsearch
    - graphite
logstash_balance:
  image: logstash:latest
  command: logstash -f /etc/logstash/conf.d/logstash.conf
  volumes:
    - ./logstash_balance/config:/etc/logstash/conf.d
  ports:
    - "5003:5003"
  links:
    - elasticsearch
    - graphite
kibana:
  build: kibana/
  volumes:
    - ./kibana/config/kibana.yml:/opt/kibana/config/kibana.yml
  ports:
    - "5601:5601"
  links:
    - elasticsearch
grafana:
  image: grafana/grafana
  ports:
    - "3000:3000"
  environment:
    - GF_SECURITY_ADMIN_USER=admin
    - GF_AUTH_GOOGLE_CLIENT_SECRET=admin
    - ELASTICSEARCH_PROTO=http
    - GRAPHITE_HOST=graphite
    - GRAPHITE_PORT=80
  links:
    - graphite
